DELETE FROM bookings;
ALTER TABLE bookings ALTER COLUMN id RESTART WITH 1;

DELETE FROM items;
ALTER TABLE items ALTER COLUMN id RESTART WITH 1;

DELETE FROM users;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;

